version: "3.9"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=141x.io
      - SUBDOMAINS=cdn,api
      - VALIDATION=http
      - CERTPROVIDER=zerossl
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL=ggcaponetto@gmail.com
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./swag/config:/config
    ports:
      - "443:443"
      - "80:80" #optional
    restart: unless-stopped
  141x-game-authorizer:
    image: "ggcaponetto/141x-game-authorizer:latest"
    container_name: 141x-game-authorizer
    environment:
      - PORT=5000
      - REACT_APP_BLOCKFROST_API_KEY_MAINNET=mainnetBZlO5gTmEra3HQClx0tavfhTs6SffTiI
      - REACT_APP_BLOCKFROST_API_KEY_TESTNET=testnetiMWOam5dRqf8xr0q0ytNhYCRRDInJRWw
      - REACT_APP_SERVER=https://game-server.141x.io
      - REACT_APP_APP_ID=the-meta
      - REACT_APP_NETWORK=mainnet
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    name: adlace