version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=141x.io
      - SUBDOMAINS=cdn,api
      - VALIDATION=http
      # - CERTPROVIDER=zerossl
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL=ggcaponetto@gmail.com
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    environment:
      - NGINX_HOST=141x.io
      - NGINX_PORT=80
    ports:
      - "5000:80"