version: "3.9"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    networks:
      - adlace
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=141x.io
      - SUBDOMAINS=cdn,api
      - VALIDATION=http
      # - CERTPROVIDER=zerossl
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL=ggcaponetto@gmail.com
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  web:
    image: nginx
    container_name: web
    networks:
      - adlace
    volumes:
      - ./templates:/etc/nginx/templates
      - 8080:8080
    environment:
      - NGINX_PORT=8080
networks:
  adlace: